-- Tables the application writes. The Nordic Supply pack ships them in its schema (with two seeded widgets); a pack
-- that does not gets them here with the same columns.
CREATE TABLE IF NOT EXISTS activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    user_id INT,
    view_name VARCHAR(40) NOT NULL,
    widget_id INT,
    prompt CLOB,
    prompt_sent CLOB,
    data_scope VARCHAR(400),
    proposal CLOB,
    decision VARCHAR(20),
    rejection_rule VARCHAR(200),
    model_name VARCHAR(80),
    finish_reason VARCHAR(40),
    input_tokens INT,
    output_tokens INT
);
CREATE TABLE IF NOT EXISTS saved_widgets (
    id INT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    widget_type VARCHAR(10) NOT NULL,
    query_sql CLOB,
    state_json CLOB,
    position INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS bulk_change_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    created_by INT NOT NULL,
    prompt CLOB NOT NULL,
    description VARCHAR(400),
    status VARCHAR(20) NOT NULL,
    applied_at TIMESTAMP,
    undone_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS bulk_change_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    product_id INT NOT NULL,
    field_name VARCHAR(40) NOT NULL,
    old_value VARCHAR(80),
    new_value VARCHAR(80),
    effective_from DATE,
    accepted BOOLEAN NOT NULL,
    price_history_id INT
);
