-- A saved dashboard for every demo user, so Insights opens with something to look at and to refine. The pack
-- seeds two widgets for Test User (ids 1 and 2); these add two more for that user and two or three for each regional
-- account manager. The queries name no country: the scoped views apply the user's region when they run.
-- state_json carries only a size; a chart without a configuration is drawn as a column chart.
INSERT INTO saved_widgets (id, user_id, title, description, widget_type, query_sql, state_json, position, created_at, updated_at) VALUES
  (3, 1, 'Backorder lines by category', 'Order lines waiting for stock, counted per product category; the categories with the most lines come first.', 'CHART', 'SELECT cat.name AS category, COUNT(*) AS backordered_lines FROM order_lines ol JOIN products p ON p.id = ol.product_id JOIN categories cat ON cat.id = p.category_id WHERE ol.status = ''BACKORDERED'' GROUP BY cat.name ORDER BY backordered_lines DESC', '{"colspan":2,"rowspan":1}', 2, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (4, 1, 'Late deliveries by carrier, August 2026', 'Deliveries in August 2026 per carrier, how many arrived after the promised delivery date, and the share that did.', 'GRID', 'SELECT s.carrier, COUNT(*) AS deliveries, SUM(CASE WHEN CAST(s.delivered_at AS DATE) > o.promised_delivery_date THEN 1 ELSE 0 END) AS late_deliveries, ROUND(100.0 * SUM(CASE WHEN CAST(s.delivered_at AS DATE) > o.promised_delivery_date THEN 1 ELSE 0 END) / COUNT(*), 0) AS late_pct FROM shipments s JOIN orders o ON o.id = s.order_id WHERE s.delivered_at >= DATE ''2026-08-01'' AND s.delivered_at < DATE ''2026-09-01'' GROUP BY s.carrier ORDER BY late_pct DESC', NULL, 3, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (5, 8, 'Orders per month, 2026', 'Sales orders placed in 2026, counted per month of placement, for the customers in your region.', 'CHART', 'SELECT FORMATDATETIME(m, ''MMM'') AS month_placed, n AS orders FROM (SELECT DATE_TRUNC(''MONTH'', placed_at) AS m, COUNT(*) AS n FROM orders WHERE placed_at >= DATE ''2026-01-01'' GROUP BY DATE_TRUNC(''MONTH'', placed_at)) ORDER BY m', NULL, 0, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (6, 8, 'Open claims by customer', 'Claims not yet resolved, closed or rejected, grouped by customer with the amount claimed and the oldest opening date; most claims first.', 'GRID', 'SELECT cu.name AS customer, cu.country, COUNT(*) AS open_claims, SUM(c.claimed_amount) AS claimed_eur, MIN(c.opened_at) AS oldest FROM claims c JOIN customers cu ON cu.id = c.customer_id WHERE c.status NOT IN (''RESOLVED'', ''CLOSED'', ''REJECTED'') GROUP BY cu.name, cu.country ORDER BY open_claims DESC, oldest', NULL, 1, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (7, 8, 'Top customers by sales, 2026', 'Customers ranked by the net value of their orders placed in 2026, cancelled orders excluded; the fifteen largest.', 'GRID', 'SELECT cu.name AS customer, cu.city, COUNT(*) AS orders, SUM(o.total_net) AS sales_eur FROM orders o JOIN customers cu ON cu.id = o.customer_id WHERE o.placed_at >= DATE ''2026-01-01'' AND o.status <> ''CANCELLED'' GROUP BY cu.name, cu.city ORDER BY sales_eur DESC LIMIT 15', NULL, 2, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (8, 9, 'Late deliveries by carrier, August 2026', 'Deliveries in August 2026 that arrived after the promised delivery date, counted per carrier.', 'CHART', 'SELECT s.carrier, COUNT(*) AS late_deliveries FROM shipments s JOIN orders o ON o.id = s.order_id WHERE CAST(s.delivered_at AS DATE) > o.promised_delivery_date AND s.delivered_at >= DATE ''2026-08-01'' AND s.delivered_at < DATE ''2026-09-01'' GROUP BY s.carrier ORDER BY late_deliveries DESC', NULL, 0, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (9, 9, 'Claims open for over 7 days', 'Claims not yet resolved, closed or rejected that were opened more than 7 days ago, oldest first.', 'GRID', 'SELECT c.claim_number, cu.name AS customer, c.claim_type, c.status, c.priority, c.opened_at, DATEDIFF(''DAY'', c.opened_at, CURRENT_TIMESTAMP) AS days_open, c.claimed_amount FROM claims c JOIN customers cu ON cu.id = c.customer_id WHERE c.status NOT IN (''RESOLVED'', ''CLOSED'', ''REJECTED'') AND c.opened_at < DATEADD(''DAY'', -7, CURRENT_TIMESTAMP) ORDER BY c.opened_at', NULL, 1, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (10, 9, 'Credit notes issued in August 2026, by reason', 'The value credited to customers in August 2026, split by the reason the credit note was issued for.', 'CHART', 'SELECT reason, SUM(amount) AS credited_eur FROM credit_notes WHERE issued_at >= DATE ''2026-08-01'' AND issued_at < DATE ''2026-09-01'' GROUP BY reason ORDER BY credited_eur DESC', NULL, 2, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (11, 10, 'Orders per month, 2026', 'Sales orders placed in 2026, counted per month of placement, for the customers in your region.', 'CHART', 'SELECT FORMATDATETIME(m, ''MMM'') AS month_placed, n AS orders FROM (SELECT DATE_TRUNC(''MONTH'', placed_at) AS m, COUNT(*) AS n FROM orders WHERE placed_at >= DATE ''2026-01-01'' GROUP BY DATE_TRUNC(''MONTH'', placed_at)) ORDER BY m', NULL, 0, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00'),
  (12, 10, 'Backordered lines by category', 'Order lines waiting for stock per product category, with the units involved and the next expected restock date.', 'GRID', 'SELECT cat.name AS category, COUNT(*) AS backordered_lines, SUM(ol.quantity) AS units, MIN(ol.expected_restock_date) AS next_restock FROM order_lines ol JOIN products p ON p.id = ol.product_id JOIN categories cat ON cat.id = p.category_id WHERE ol.status = ''BACKORDERED'' GROUP BY cat.name ORDER BY backordered_lines DESC', NULL, 1, TIMESTAMP '2026-09-07 09:30:00', TIMESTAMP '2026-09-07 09:30:00');
